### PR TITLE
Sponsor changes

### PR DESCRIPTION
**Pull request by aniarya82**
screen shot 2015-10-06 at 2 49 52 am
screen shot 2015-10-06 at 3 09 26 am
Other Sponsor page in same template as Sponsor 2015
screen shot 2015-10-06 at 3 12 10 am

### CODE REVIEW

**Comment by aniarya82** [comment]
@icyflame Did you got chance to take a look at this??

**Comment by icyflame** [comment]
@aniarya82 Not yet. I will merge it if it affects only the UI.

**Comment by aniarya82** [comment]
You could tell me about the other sponsor page changes that are required. I
could do the needful.

On Fri, Dec 18, 2015 at 11:49 AM, Siddharth Kannan <notifications@github.com

> wrote:
> 
> Merged #64
> https://github.com/students-alumni-cell-iitkgp/aam-2016/pull/64.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/students-alumni-cell-iitkgp/aam-2016/pull/64#event-495509636
> .

## 

_Regards,_

_Hiten Chowdhary_

_Undergraduate Student_

_Department of Mathematics_

_IIT Kharagpur_

_Ph: +919800111032_

**Comment by icyflame** [comment]
@aniarya82 Check #66 , you can implement any layout that you feel is better than the present one.

**Pull request merged**
