### PR TITLE
changes in spons pages done

### PR DESCRIPTION
**Pull request by punit121**
changes done

### CODE REVIEW

**Comment by icyflame** [comment]
@punit121 Remove the background color of `Co-Sponsors`, `Major Sponsors` etc.

**Comment by icyflame** [comment]
@punit121 
1. All headings such as `Co-Sponsors`, `Major Sponsors` etc need to be made bold and slightly larger font size.
2. Reduce size of HMEL logo size in the 2014 page
3. increase spacing between last two lines of sponsors in the 2014 page.

In general, glance over all pages to make sure that they look good, from an aesthetic POV.

**Comment by punit121** [comment]
required changes done

**Comment by icyflame** [comment]
Sponsors 2015 page looks haphazard. Reduce size of all logos. Make sure that they are in the center, horizontally and vertically. Stick to 4 column table. Don't keep switching between 3 columns and 4 columns, very distracting.

**Comment by punit121** [comment]
size of all logos changed also spacing between lines also increased but as event sponsors has 7 companies so a 4 row combination is not suitable for that also online media partners has 2 companies
and luxury hotel partner has 1 company so i have fitted these in a row of 3 
suggest any way for table of 4 rows

**Comment by punit121** [comment]
some more changes done in spons 14 and spons 15 .rows of 4 made to some extent in spons 15 .

**Comment by icyflame** [comment]
@punit121 
1. Reduce `hmel` logo even further.
2. Put a `<hr>` between two sections in all sponsor pages (like `Event Sponsors` and `Gift Sponsors` in 2014)
3. Put 4 columns everywhere, in 2015. Three columns at the end of Gift Sponsors. Change that to three.

**Don't define HEIGHT and WIDTH for any element. Define ONLY height or ONLY width, that way the aspect ratio will be preserved.**

**Comment by punit121** [comment]
all required changes done 
Pl check

**Comment by icyflame** [comment]
@punit121 Thanks! Great work :+1:

**Pull request merged**
