### PR TITLE
Add the sponsors 2016 page

### PR DESCRIPTION
**Pull request by uagarwal744**
@icyflame Please check it, I have changed the index page to flash page as asked by Akash. Also the original index page is renamed to home.php

### CODE REVIEW

**Comment by icyflame** [comment]
What do you mean "flash page"?

**Comment by uagarwal744** [comment]
screenshot 23
@icyflame 
Index will look like this, on clicking it will redirect to the meet website

**Comment by icyflame** [comment]
1. What about mobile?
2. It is not obvious that you have to click on it, write somewhere on the
   page, and this should be prominent.

**Comment by icyflame** [comment]
@uagarwal744 

Can you post screenshots:
- the navbar, with sponsors drop down opened on homepage
- the sponsors 2016 page itself

**Comment by uagarwal744** [comment]
@icyflame 
Here are the screenshots. Also i found some problem in index page, which i have fixed in the latest commit.
screenshot 25
screenshot 26
screenshot 27

**Pull request merged**
